// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nettium_Test.Persistence.Datas;

#nullable disable

namespace Nettium_Test.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523024134_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");
#pragma warning restore 612, 618
        }
    }
}
